POST http://localhost:3333/videos
Content-Type: application/json


{
    "title" : "Video nodejs",
    "description": "Esse é o video do ano",
    "duration": 120
}

###
GET http://localhost:3333/videos?search=node


###

PUT http://localhost:3333/videos/
Content-Type: application/json


{
    "title" : "Videeeeeo 03 node",
    "description": "Esse é o video",
    "duration": 100
}


### 
DELETE http://localhost:3333/videos/